<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Attach Files_training-file-input-icon</name>
   <tag></tag>
   <elementGuidId>0a16b12c-09e9-428e-aa31-258a43124807</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.training-file-input-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>79c4f518-08d5-48bf-b264-43b8867a1802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/dist/img/sks/ico_export.svg</value>
      <webElementGuid>0c9bf4df-007d-43d6-ba12-ab1427c58add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>training-file-input-icon</value>
      <webElementGuid>e8f25d3c-1b09-4383-86c0-c23d3d4d4a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;hold-transition skin-blue sidebar-mini&quot;]/app-root[1]/app-admin[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/app-training-create[1]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;box-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/label[@class=&quot;training-file-input&quot;]/img[@class=&quot;training-file-input-icon&quot;]</value>
      <webElementGuid>be768b4c-5158-4e43-b595-f7fc66132d43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/img</value>
      <webElementGuid>bba58017-e74d-4dbe-8851-e6571fbd1de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/dist/img/sks/ico_export.svg']</value>
      <webElementGuid>45ffc1fa-24da-43e4-854e-cd56e6bb5b87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
